# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd77ae3fd4e6747d37e386a576b176648a8d27388d109f7b9dbd2974e3460757bbd113da18bfa970b6f64581a89cf577b46d360bf9abb09760a471db3e51d43

test:
  secret_key_base: aec6b15c0367a572347da20080d61a756a7d64eebcb4b7875386ffecf55c987c4751cd62089a49b383d7be959815792a57289f1701fb5b3a21213c5df008c60d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
